services:
  - type: web
    name: my-node-app
    runtime: node
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      npm install
    startCommand: node server.js
    env:
      - name: PORT
        value: 3000
      - name: NODE_ENV
        value: production